### ISSUE TITLE
Solver and version column in search table

### ISSUE THREAD

**Issue by ambros-gleixner** [ambros-gleixner/rubberband#21]
Currently the search table misses columns showing the solver name and the solver version and the LP solver version. Maybe it makes sense to display this all in one column e.g. "SCIP 4.0.0.2 (SoPlex 3.0.0.1)", but it must work generically, also for other solvers in the future that have empty LP solver column.

**Comment by fschloesser** [comment]
What do you mean by "work generically"? At the moment the LPsolver column is more or less as important as the other ones. i would leave Solver and LPSolver as two seperate columns for the time being. It however should not be a problem if there is no LPSolver specified.

**Comment by ambros-gleixner** [comment]
I just mean it should work if LPSolver (and LPSolver version) is empty.

**Comment by ambros-gleixner** [comment]
Can you make Solver and LPSolver the leftmost columns right of "Details"?

**Comment by ambros-gleixner** [comment]
LPSolver right of Solver.

**Comment by fschloesser** [comment]
This has been resolved

**Comment by ambros-gleixner** [comment]
Nice.
