### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by ambros-gleixner** [ambros-gleixner/rubberband#24]
These are not high priority, but I wanted to create an issue to collect design changes that would enhance the user experience.  General:

* [x] A monospaced font: although this sounds very oldschool, I am convinced it improves readability of tables; there are some well-designed monospace fonts out there, e.g. https://fonts.google.com/specimen/Fira+Mono, which could even be good for all text.
* [x] Integrate the menu on the left (Search, ...) into the top bar in order to maximize usage of screen width.
* [x] Remove horizontally separating lines from tables (not 100% sure, let's try).
* [x] Rename the header "Result" to "Evaluate".
* [x] Update the bug report link in FAQ.
* [x] Update or remove the "500" explanation under FAQ.
* [x] Rename FAQ to Help.

In the details table
* [x] Replace the harsh red and green by something "nicer".
* [x] Move the search field to the left.
* [x] Move the "How do I interpret the comparison view?" text as an explanation below the detailed table.

In the Ipet table:
* [x] Right align numbers.
* [x] Remove vertically separating lines within one group.
* [x] Add a background color to columns _abort_, ..., _unkn_ and the Q columns 
* [x] Print instance numbers (in the first columns) as integers, without .0.
* [x] Format time, node, Q values, and p values with less precision; 3 digits should suffice, for time and nodes even 1.
* [x] Remove or shorten the "_shmean".

**Comment by fschloesser** [comment]
move navigation to top and repair mobile design: https://github.com/ambros-gleixner/rubberband/commit/a9177b6cac7f2cd963575a0c51feb3d39c8591ab

**Comment by fschloesser** [comment]
Do we want a monospace font for everything? I would only use one only for the tables.

**Comment by ambros-gleixner** [comment]
Me, too, only for the tables.  But please replace the other text and headers also by some nicer font, maybe also from the Firas.

**Comment by ambros-gleixner** [comment]
The bright background of the top navigation bar is very close to the white of the content page.  Maybe have blue background everywhere (like GitHub is in black).

And of course we also need a similarly cool logo like Octocat.

**Comment by fschloesser** [comment]
Everything here has been addressed, except the logo.

**Comment by ambros-gleixner** [comment]
Three things are still open, I unchecked the boxes:
* color Q columns
* three digit p columns
* search boxes to the left

The logo can wait until we have some inspiration.  :)

Thanks!

**Comment by ambros-gleixner** [comment]
Yep!
