### ISSUE TITLE
Remove or replace huge log files from tests/data

### ISSUE THREAD

**Issue by ambros-gleixner** [ambros-gleixner/rubberband#27]
IP_0s_1s and MMM should not be necessary, short should suffice for the tests, right?  Maybe even one is enough?

**Comment by GregorCH** [comment]
The large ones should not be necessary anymore since we have Meta files. Individual, small log files are easy to maintain. Ideally, different cases are covered, e.g., an infeasible instance, an optimally solved instance, a time out, and one where the solution is infeasible within tolerances.

**Comment by fschloesser** [comment]
I shortened the logfiles as @GregorCH suggested and remove some of the big ones. Though i don't know how to identify an instance where the solution is infeasible within tolerances.

**Comment by ambros-gleixner** [comment]
> Though i don't know how to identify an instance where the solution is infeasible within tolerances.

Is this one good?

https://rubberband.zib.de/result/AV9SJRgeuKh1YUoBNPrW/instance/AV9SJSduuKh1YUoBNPuS

**Comment by fschloesser** [comment]
Can i take that logfile in a reduced size and add it to the rubberband testdata?

**Comment by ambros-gleixner** [comment]
Not sure what you are asking.

**Comment by fschloesser** [comment]
i wanted to make sure that it is alright that i add the logfile to this github repository

**Comment by ambros-gleixner** [comment]
Yes.
