### ISSUE TITLE
Preserve upload time and uploader at reimport

### ISSUE THREAD

**Issue by ambros-gleixner** [ambros-gleixner/rubberband#28]
When reimporting a testrun, currently upload time and uploader change to now and the person who performs the reimport.  This should not happen: it can make testruns hard to find if you don't know about the reimport.

**Comment by fschloesser** [comment]
Rubberband will now save time and person for both upload and last reimport. 

Which of these four information should be displayed in the tables? I like the idea that last modified testruns are displayed at the top of the table.

**Comment by ambros-gleixner** [comment]
Agreed.  At some point it would be nice to be able to sort this table, then that question becomes less important.

**Comment by ambros-gleixner** [comment]
I am reopening this, because the search page should have an (original) uploader name field to search.  (This is what is constant and people remember.)

**Comment by fschloesser** [comment]
changed that in https://github.com/ambros-gleixner/rubberband/commit/3c2b1943b7f2b1591d830ea6ed49ceaf680a7d04
