### ISSUE TITLE
SoPlex hash

### ISSUE THREAD

**Issue by gerald-gamrath** [ambros-gleixner/rubberband#31]
Right now, you have to look into the log file to find out the git hash of the SoPlex version used for a run. It would be nice if this would be somewhere at the top of the meta data.

Corresponding ipet issue: https://github.com/GregorCH/ipet/issues/57

**Comment by GregorCH** [comment]
I added the parsing functionality to the SCIPSolver class in IPET. The corresponding datakey is "SpxGitHash"

**Comment by fschloesser** [comment]
Implemented with https://github.com/ambros-gleixner/rubberband/commit/d4a14cf3614315d3596a0ec2d915a7961fc6e525
