### ISSUE TITLE
Add sort functionality back to Ipet table

### ISSUE THREAD

**Issue by ambros-gleixner** [ambros-gleixner/rubberband#33]
This would be super useful, only we need to ensure that the groups can be sorted as in the XML schema.

A quick workaround would be to simply number them explicitly 1. all, 2. clean, ... in the XMLs, but maybe there is a better way.

Anyway, let's look at it together on your local development version before it goes online.

**Comment by GregorCH** [comment]
Can you be more specific what you would like to sort? IPET usually comes with two tables, the "long table" and the "aggregate table". Care is taken that the groups appear in the order in which they are defined. We once had a sortlevel functionality to determine whether the columns of the long table
should appear in "Settings" order (or rubberbandid, or anything else),
```
Setting       A         A       B           B   ...
             Time Nodes Time  Nodes
```

or  in Column order
```
Setting       A         B       A           B   ...
             Time  Time Nodes  Nodes
```

**Comment by ambros-gleixner** [comment]
I thought about the automatic sorting that comes with the javascript datatables, like in the details table or the Ipet long table.

@fschloesser had already activated this once for the aggregate table, and then I told her to take it out because it "destroyed" the order of rows as specified in the XML. But I think it is useful also for the aggregate tables if we can ensure that the rows (subsets) are kept in the same order as specified in the XML, if only by a workaround like numbering them.

I hope that is clearer now?

**Comment by GregorCH** [comment]
I always thought that the sorting is only relevant for the mixed rubberband-indices, which are filled in afterwards and therefore confuse the normal sorting of pandas data frames.

Without giving this too much thought, I would recommend to automate the indexing of the group names, because this definitely sucks as soon as you need to rename all of the groups in case you add one up front.

**Comment by fschloesser** [comment]
I added this in https://github.com/ambros-gleixner/rubberband/pull/26/commits/3258049328b71aac6df6baae20ff04f0e50baa67

**Comment by ambros-gleixner** [comment]
The sorting is great, thanks.  One open point: the automatic numbering of groups must be adjusted to 01, 02, 03, ... otherwise the order is 1, 10, 11, ..., 2, 3, 4, ...
