### ISSUE TITLE
Some formatting issues in the Details table

### ISSUE THREAD

**Issue by GregorCH** [ambros-gleixner/rubberband#34]
- all numeric columns display a left-aligned string "--" for missing values which looks weird.
- An infinite gap is not displayed consistently in the Gap column if the infinity is different from 1e+20, probably a hard-coded value somewhere
- sometimes tiny differences in the primal bounds/dual bounds do not have a visible coloring. Maybe use some minimum redness/greenness to visibly distinguish instances where nothing changed from those where it did.

**Comment by fschloesser** [comment]
I addressed the points. I hope i did not miss anything.
