### ISSUE TITLE
Feature Request: Extend download functionality

### ISSUE THREAD

**Issue by GregorCH** [ambros-gleixner/rubberband#35]
It is currently a tedious process to download the out,err,meta,set-files that a colleague uploaded to rubberband. I suggest to extend the download functionality by a "tbz2" function (next to plaintext, gzip).
If selected, rubberband should

1) group *all* files that belong to the current comparison, i.e., all out/err/meta/set files for all involved test runs, from elasticsearch.
2) create a single, temporary tbz2 (bzip beats gzip) archive for download
3) delete the archive after the download has been completed.

**Comment by fschloesser** [comment]
this has been dealt with in commit 3b6c45e842714aa4e5e703044d025c271047ee0b

**Comment by GregorCH** [comment]
I tried it, works very nicely. Two comments: Is there a particular reason why you made a new button instead of extending the available download menu?
Second, I assume that it is necessary to store the log files under the cryptic hash directories, because there could be name collisions.

**Comment by GregorCH** [comment]
Oh, I just realized that the downloaded archive uses wrong file names. Every file has the .out extension, followed by the specific extension. This yields names like *.out.meta, .out.err, etc.
