### ISSUE TITLE
Feature Request. New Console Log View of an IPET evaluation

### ISSUE THREAD

**Issue by GregorCH** [ambros-gleixner/rubberband#38]
We always improve IPET's output and warning messages. It would be nice to provide a view of IPET's evaluation warning and error output in  a dedicated window in the Summary tab. Then, we can more easily spot problems if one wants to be informed if there were any problems such as a nonexisting entry of an instance in the data base, or these annoying warning messages from numpy.

**Comment by fschloesser** [comment]
This has been completed with https://github.com/ambros-gleixner/rubberband/commit/ab2bb280f7389be35caaa0e4c6113820438a71ba
