### ISSUE TITLE
Feature Request: Basic visualization of a column of the displayed table

### ISSUE THREAD

**Issue by GregorCH** [ambros-gleixner/rubberband#40]
It would be awesome to quickly visualize the table data. A simple start would be the following:

The user selects a column of the table by name from a drop down menu. The values of this column are then sorted and displayed as bars in two plots, with and without logarithmic y axis.

![rplot](https://user-images.githubusercontent.com/17698778/43133347-c2f50fc6-8f3e-11e8-8a27-f199c80e9ff3.png)

**Comment by fschloesser** [comment]
implemented by https://github.com/ambros-gleixner/rubberband/commit/d7b6fdba2379b0d8dbbf039f33841ec800b40022

**Comment by GregorCH** [comment]
So awesome! Thanks!
