### ISSUE TITLE
Feature Request: "Shopping Cart"

### ISSUE THREAD

**Issue by GregorCH** [ambros-gleixner/rubberband#41]
The search view is restricted to 100 entries. It has now happened to me that I wanted to compare two testruns with different uploader, settings name, test set, and upload date, A and B. I can search and find A easily and select it. However, it is impossible now to search for B without losing the selection A.

I can imagine 3 different ways to cope with this, the easiest of which I would call a "shopping cart".

1. Shopping cart: Like in online shopping, create a feature that saves selected runs permanently during repeated queries. I can select A, add it to my shopping cart, and continue searching for B, select B as well, and finally compare the two.

2. Allow filter disjunction. Extend the filter functionality of the search view. Below every filter, add a plus button that can be clicked to select a second, third, and so on option. I could select "A" as setting, then click the + button to also select another setting "B".

3. Allow tag assignment independently from uploading. I could tag A and B with the same tag, and then search for the tag. This option is, of course, less cool and functional than the two others.

**Comment by fschloesser** [comment]
For the time now you can achieve this the following way:
- You can set the limit to a different number in the search fields
- you can use the "+" in the comparison view to add comparisons

In the future i will work on improving this.
